# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DicTypeMstInputProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DicTypeMstInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\027TomTaw.eWordIMCIS.Proto'),
  serialized_pb=_b('\n\x1a\x44icTypeMstInputProto.proto\"t\n\x14\x44icTypeMstInputProto\x12\x11\n\ttypeClass\x18\x01 \x01(\t\x12\x10\n\x08typeCode\x18\x02 \x01(\t\x12\x10\n\x08typeName\x18\x03 \x01(\t\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\x12\x13\n\x0b\x63urrentPage\x18\x05 \x01(\x05\x42\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3')
)




_DICTYPEMSTINPUTPROTO = _descriptor.Descriptor(
  name='DicTypeMstInputProto',
  full_name='DicTypeMstInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeClass', full_name='DicTypeMstInputProto.typeClass', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeCode', full_name='DicTypeMstInputProto.typeCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeName', full_name='DicTypeMstInputProto.typeName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='DicTypeMstInputProto.pageSize', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='DicTypeMstInputProto.currentPage', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['DicTypeMstInputProto'] = _DICTYPEMSTINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DicTypeMstInputProto = _reflection.GeneratedProtocolMessageType('DicTypeMstInputProto', (_message.Message,), {
  'DESCRIPTOR' : _DICTYPEMSTINPUTPROTO,
  '__module__' : 'DicTypeMstInputProto_pb2'
  # @@protoc_insertion_point(class_scope:DicTypeMstInputProto)
  })
_sym_db.RegisterMessage(DicTypeMstInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
