# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PatientInputProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from UserOrgInfoProto import Proto_pb2 as UserOrgInfoProto_dot_Proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PatientInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\037TomTaw.eWordIMCIS.WebAPI.Models'),
  serialized_pb=_b('\n\x17PatientInputProto.proto\x1a\x16UserOrgInfoProto.Proto\"\xee\x02\n\x11PatientInputProto\x12\x13\n\x0bpatientName\x18\x01 \x01(\t\x12\x10\n\x08iDCardNo\x18\x02 \x01(\t\x12\x14\n\x0chealthCardNO\x18\x03 \x01(\t\x12\x13\n\x0binsuranceID\x18\x04 \x01(\t\x12\x1a\n\x12userOrganizationID\x18\x05 \x01(\t\x12\x13\n\x0bquickSearch\x18\x06 \x01(\t\x12\x10\n\x08pageSize\x18\x07 \x01(\x05\x12\x13\n\x0b\x63urrentPage\x18\x08 \x01(\x05\x12\r\n\x05token\x18\t \x01(\t\x12#\n\x08userInfo\x18\n \x01(\x0b\x32\x11.UserOrgInfoProto\x12\x15\n\risInteragency\x18\x0b \x01(\t\x12\x19\n\x11isInteragencyExam\x18\x0c \x01(\t\x12\x1b\n\x13IsInteragencyClinic\x18\r \x01(\t\x12\x1e\n\x16IsInteragencyStatistic\x18\x0e \x01(\t\x12\x0c\n\x04test\x18\x0f \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3')
  ,
  dependencies=[UserOrgInfoProto_dot_Proto__pb2.DESCRIPTOR,])




_PATIENTINPUTPROTO = _descriptor.Descriptor(
  name='PatientInputProto',
  full_name='PatientInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='patientName', full_name='PatientInputProto.patientName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iDCardNo', full_name='PatientInputProto.iDCardNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='healthCardNO', full_name='PatientInputProto.healthCardNO', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insuranceID', full_name='PatientInputProto.insuranceID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userOrganizationID', full_name='PatientInputProto.userOrganizationID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quickSearch', full_name='PatientInputProto.quickSearch', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='PatientInputProto.pageSize', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='PatientInputProto.currentPage', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='PatientInputProto.token', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='PatientInputProto.userInfo', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isInteragency', full_name='PatientInputProto.isInteragency', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isInteragencyExam', full_name='PatientInputProto.isInteragencyExam', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsInteragencyClinic', full_name='PatientInputProto.IsInteragencyClinic', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsInteragencyStatistic', full_name='PatientInputProto.IsInteragencyStatistic', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test', full_name='PatientInputProto.test', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=418,
)

_PATIENTINPUTPROTO.fields_by_name['userInfo'].message_type = UserOrgInfoProto_dot_Proto__pb2._USERORGINFOPROTO
DESCRIPTOR.message_types_by_name['PatientInputProto'] = _PATIENTINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PatientInputProto = _reflection.GeneratedProtocolMessageType('PatientInputProto', (_message.Message,), {
  'DESCRIPTOR' : _PATIENTINPUTPROTO,
  '__module__' : 'PatientInputProto_pb2'
  # @@protoc_insertion_point(class_scope:PatientInputProto)
  })
_sym_db.RegisterMessage(PatientInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
